### ISSUE TITLE
Please add Razer Barracuda X

### ISSUE THREAD

**Issue by rellikpd** [Tekk-Know/RazerBatteryTaskbar#13]
I love my Razer headphones, but HATE the Razer software. Please add support for the Barracuda X. I tried the app as it is released now just hoping it might work, but it does not. And I can connect to my phone to read the battery, but I don't want my headphones dual-casting and i want to tell at a glance, not pick my phone up. Thank you!

**Comment by Tekk-Know** [comment]
Sorry this is out of scope of the current project.
