### ISSUE TITLE
How do you pull the battery information

### ISSUE THREAD

**Issue by ashley-gibbs** [Tekk-Know/RazerBatteryTaskbar#14]
Hi there. Can I ask how it is that you actually grab the battery level from these devices. I am working on a plugin for an application called SimHub and I would like to add in the ability to pull battery level indicators for various wireless headsets. I am struggling to find where it is I can actually call this information from in my code. Any help would be greatly appreciated as I am used to working with game readers and telemetry rather than pulling info from devices.

**Comment by Tekk-Know** [comment]
You can check the code, but it's basically a combination of a USB lib and transmission codes which correspond to "commands" which exist in the devices firmware. For each device you have to figure out how to ask for battery level.
