### ISSUE TITLE
Windows 11 - LIBUSB_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by brozikcz** [Tekk-Know/RazerBatteryTaskbar#17]
Hi guys,

do you have any idea how to make works the BlackShark V2 Pro RZ04-0322 (2020 Version) on Windows 11? I found some magic with reinstall driver with Zadig but I don't want to lost about Razer features. 

```
npm run start

> razerbatterytaskbar@1.0.6 start
> electron-forge start

√ Checking your system
√ Locating application
√ Loading configuration
√ Preparing native dependencies: 1 / 1 [0.5s]
√ Running generateAssets hook


Error: claimInterface error: Error: LIBUSB_ERROR_NOT_SUPPORTED
```

**Comment by Tekk-Know** [comment]
@brozikcz Have you tried installing the Libusb-WinUSB driver?
