### ISSUE TITLE
Undefined%

### ISSUE THREAD

**Issue by DrunkCodeStealer** [Tekk-Know/RazerBatteryTaskbar#18]
Anyone else have undefined%
I have a viper ultimate, and on 1.0.0/1.0.1 it shows this:
![grafik](https://github.com/Tekk-Know/RazerBatteryTaskbar/assets/166299170/6c3453a5-f5c1-4ed2-95bf-c663a1a1fa67)

on 1.0.5 it looks like this:
![grafik](https://github.com/Tekk-Know/RazerBatteryTaskbar/assets/166299170/63428204-f81f-4b65-a056-3828a6d8add5)

**Comment by Tekk-Know** [comment]
Working on an updated release for this.
